version: '3'
services:
    rabbitmq:
        container_name: rmq_essentials
        image: rabbitmq:3-management
        restart: unless-stopped
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=pwd
        volumes:
            - essentialsvol:/var/lib/rabbitmq
        ports:
            - 5672:5672
            - 5673:5673
            - 15672:15672
            - 15674:15674
            - 15671:15671
        networks:
            - essentials
networks:
    essentials:
        driver: bridge
volumes:
    essentialsvol:
        driver: local
